/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLessonQaRouteImport } from './routes/api/lesson-qa'
import { Route as ApiGenerateLessonRouteImport } from './routes/api/generate-lesson'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonQaRoute = ApiLessonQaRouteImport.update({
  id: '/api/lesson-qa',
  path: '/api/lesson-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLessonRoute = ApiGenerateLessonRouteImport.update({
  id: '/api/generate-lesson',
  path: '/api/generate-lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate-lesson': typeof ApiGenerateLessonRoute
  '/api/lesson-qa': typeof ApiLessonQaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate-lesson': typeof ApiGenerateLessonRoute
  '/api/lesson-qa': typeof ApiLessonQaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/generate-lesson': typeof ApiGenerateLessonRoute
  '/api/lesson-qa': typeof ApiLessonQaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/api/generate-lesson' | '/api/lesson-qa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/api/generate-lesson' | '/api/lesson-qa'
  id: '__root__' | '/' | '/auth' | '/api/generate-lesson' | '/api/lesson-qa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiGenerateLessonRoute: typeof ApiGenerateLessonRoute
  ApiLessonQaRoute: typeof ApiLessonQaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson-qa': {
      id: '/api/lesson-qa'
      path: '/api/lesson-qa'
      fullPath: '/api/lesson-qa'
      preLoaderRoute: typeof ApiLessonQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-lesson': {
      id: '/api/generate-lesson'
      path: '/api/generate-lesson'
      fullPath: '/api/generate-lesson'
      preLoaderRoute: typeof ApiGenerateLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiGenerateLessonRoute: ApiGenerateLessonRoute,
  ApiLessonQaRoute: ApiLessonQaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
