/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as ApiLessonQaRouteImport } from './routes/api/lesson-qa'
import { Route as ApiGenerateLessonRouteImport } from './routes/api/generate-lesson'

const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLessonQaRoute = ApiLessonQaRouteImport.update({
  id: '/api/lesson-qa',
  path: '/api/lesson-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateLessonRoute = ApiGenerateLessonRouteImport.update({
  id: '/api/generate-lesson',
  path: '/api/generate-lesson',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lessons': typeof LessonsRoute
  '/api/generate-lesson': typeof ApiGenerateLessonRoute
  '/api/lesson-qa': typeof ApiLessonQaRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lessons': typeof LessonsRoute
  '/api/generate-lesson': typeof ApiGenerateLessonRoute
  '/api/lesson-qa': typeof ApiLessonQaRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lessons': typeof LessonsRoute
  '/api/generate-lesson': typeof ApiGenerateLessonRoute
  '/api/lesson-qa': typeof ApiLessonQaRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lessons'
    | '/api/generate-lesson'
    | '/api/lesson-qa'
    | '/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lessons'
    | '/api/generate-lesson'
    | '/api/lesson-qa'
    | '/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/lessons'
    | '/api/generate-lesson'
    | '/api/lesson-qa'
    | '/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LessonsRoute: typeof LessonsRoute
  ApiGenerateLessonRoute: typeof ApiGenerateLessonRoute
  ApiLessonQaRoute: typeof ApiLessonQaRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lesson-qa': {
      id: '/api/lesson-qa'
      path: '/api/lesson-qa'
      fullPath: '/api/lesson-qa'
      preLoaderRoute: typeof ApiLessonQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-lesson': {
      id: '/api/generate-lesson'
      path: '/api/generate-lesson'
      fullPath: '/api/generate-lesson'
      preLoaderRoute: typeof ApiGenerateLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LessonsRoute: LessonsRoute,
  ApiGenerateLessonRoute: ApiGenerateLessonRoute,
  ApiLessonQaRoute: ApiLessonQaRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
